FROM ubuntu:bionic
MAINTAINER manuel.peuster@uni-paderborn.de

RUN apt-get update && apt-get install -y \
    net-tools \
    iputils-ping \
    iproute2 \
    libpcap-dev \
    gcc \
    g++

CMD /bin/bash
